packages:
  - tooling/*
resolvePeersFromWorkspaceRoot: false
onlyBuiltDependencies:
  - esbuild
  - ffmpeg-static
  - lefthook
  - msw
  - sharp
minimumReleaseAge: 0
allowBuilds:
  bufferutil: false
  esbuild: true
  ffmpeg-static: true
  ip-set: true
  lefthook: true
  msw: true
  node-datachannel: true
  sharp: true
  utf-8-validate: false
  utp-native: false
